# Generated by Django 4.1.1 on 2022-10-01 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='简介'),
            preserve_default=False,
        ),
    ]
