# Generated by Django 4.1 on 2022-10-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=128, verbose_name='番剧名')),
                ('episode', models.IntegerField(verbose_name='话数')),
                ('director', models.CharField(max_length=128, verbose_name='导演')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorAnimeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('aid', models.IntegerField(verbose_name='aid')),
                ('title', models.CharField(max_length=128, verbose_name='番剧名')),
                ('episode', models.IntegerField(verbose_name='话数')),
                ('director', models.CharField(max_length=128, verbose_name='导演')),
                ('type', models.IntegerField(default=1, verbose_name='类型')),
                ('score', models.IntegerField(default=5, verbose_name='评分')),
                ('comment', models.CharField(max_length=1024, verbose_name='吐槽')),
            ],
        ),
    ]
