# Generated by Django 4.1 on 2022-10-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_rename_animeinformation_animedata_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimeData',
            new_name='AnimeInformation',
        ),
        migrations.RenameModel(
            old_name='UserFavorAnime',
            new_name='UserFavorAnimeList',
        ),
    ]
