# Generated by Django 4.1 on 2022-10-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_rename_animeinformation_animedata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFavorAnime',
        ),
    ]
