# Generated by Django 4.1 on 2022-10-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_statetousername'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsernameToToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('access_token', models.CharField(max_length=256)),
                ('refresh_token', models.CharField(max_length=256)),
                ('uid', models.CharField(max_length=64)),
            ],
        ),
    ]
