# Generated by Django 4.1 on 2022-10-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_usernametotoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernametotoken',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
