# Generated by Django 4.1 on 2022-10-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('client_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=256)),
                ('time', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(max_length=128)),
            ],
        ),
    ]
