# Generated by Django 4.1 on 2022-10-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_authorizationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=256)),
                ('token_type', models.CharField(max_length=256)),
                ('expires_in', models.IntegerField(default=60)),
                ('refresh_token', models.CharField(max_length=256)),
                ('scope', models.CharField(default='default', max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='authorizationcode',
            name='scope',
            field=models.CharField(default='default', max_length=128),
        ),
    ]
