# Generated by Django 4.1 on 2022-10-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_accesstoken_alter_authorizationcode_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token_type',
            field=models.CharField(default='bearer', max_length=256),
        ),
    ]
