# Generated by Django 4.1 on 2022-10-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_accesstoken_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
