# Generated by Django 4.1 on 2022-10-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0006_accesstoken_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='redirect_url',
            new_name='redirect_uri',
        ),
    ]
