# Generated by Django 4.1 on 2022-10-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0007_rename_redirect_url_application_redirect_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationcode',
            name='expires_in',
            field=models.IntegerField(default=600),
        ),
    ]
