# Generated by Django 4.1 on 2022-10-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0008_authorizationcode_expires_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeToUsername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='expires_in',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='authorizationcode',
            name='expires_in',
            field=models.IntegerField(default=3600),
        ),
    ]
