# Generated by Django 4.1 on 2022-10-04 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0009_codetousername_alter_accesstoken_expires_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetousername',
            name='auth_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
