# Generated by Django 4.1 on 2022-10-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0010_codetousername_auth_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenToUsername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=32)),
            ],
        ),
    ]
