# Generated by Django 4.1 on 2022-10-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0012_statetousername'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StateToUsername',
        ),
    ]
