# Generated by Django 4.1 on 2022-10-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0013_delete_statetousername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='expires_in',
            field=models.IntegerField(default=3600),
        ),
        migrations.AlterField(
            model_name='authorizationcode',
            name='expires_in',
            field=models.IntegerField(default=60),
        ),
    ]
