# Generated by Django 4.1 on 2022-10-07 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
    ]
