# Generated by Django 4.1 on 2022-10-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_friendsrequest_userrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendsrequest',
            name='msg',
            field=models.CharField(default='qwq', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendsrequest',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
