# Generated by Django 4.1 on 2022-10-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_friendsrequest_msg_alter_friendsrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendsrequest',
            name='username_from',
            field=models.CharField(default='qwq', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendsrequest',
            name='username_to',
            field=models.CharField(default='qwq', max_length=32),
            preserve_default=False,
        ),
    ]
